version: '3'
services:

  db:

    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    networks:
      - app-network


  app:

    build: .
    volumes:
      - .:/src
      - ./migrations:/src/migrations
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network


  test:
  
    build: .
    volumes:
      - .:/src
      - ./migrations:/src/migrations
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: test
    depends_on:
      - db
    command: pytest /src/tests
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:

