"""Roles

Revision ID: 459219acd400
Revises: 5cc06c832caf
Create Date: 2024-02-18 21:55:42.263832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '459219acd400'
down_revision: Union[str, None] = '80f85d2a898c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE TYPE role as ENUM('admin', 'moderator', 'user')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('admin', 'moderator', 'user', name='role'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.execute('DROP TYPE role')
    # ### end Alembic commands ###
