"""images and tags

Revision ID: 5cc06c832caf
Revises: 5f7d466187e6
Create Date: 2024-02-17 00:46:50.694142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cc06c832caf'
down_revision: Union[str, None] = '4be3ffccbb67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('note_m2m_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('images', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('images', sa.Column('url', sa.String(length=200), nullable=True))
    op.add_column('images', sa.Column('identifier', sa.String(length=40), nullable=True))
    op.add_column('images', sa.Column('description', sa.String(length=250), nullable=True))
    op.create_unique_constraint(None, 'images', ['identifier'])
    op.create_foreign_key(None, 'images', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_constraint(None, 'images', type_='unique')
    op.drop_column('images', 'description')
    op.drop_column('images', 'identifier')
    op.drop_column('images', 'url')
    op.drop_column('images', 'user_id')
    op.drop_table('note_m2m_tag')
    op.drop_table('tags')
    # ### end Alembic commands ###
